// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package core

import (
	"encoding/json"

	"github.com/luxfi/geth/common"
	"github.com/luxfi/geth/common/hexutil"
	"github.com/luxfi/geth/common/math"
	"github.com/luxfi/geth/core/types"
	"github.com/luxfi/geth/params"
)

var _ = (*genesisSpecMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (g Genesis) MarshalJSON() ([]byte, error) {
	type Genesis struct {
		Config        *params.ChainConfig                        `json:"config"`
		Nonce         math.HexOrDecimal64                        `json:"nonce"`
		Timestamp     math.HexOrDecimal64                        `json:"timestamp"`
		ExtraData     hexutil.Bytes                              `json:"extraData"`
		GasLimit      math.HexOrDecimal64                        `json:"gasLimit"   gencodec:"required"`
		Difficulty    *math.HexOrDecimal256                      `json:"difficulty" gencodec:"required"`
		Mixhash       common.Hash                                `json:"mixHash"`
		Coinbase      common.Address                             `json:"coinbase"`
		Alloc         map[common.UnprefixedAddress]types.Account `json:"alloc"      gencodec:"required"`
		AirdropHash   common.Hash                                `json:"airdropHash,omitempty"`
		AirdropAmount *math.HexOrDecimal256                      `json:"airdropAmount,omitempty"`
		AirdropData   []byte                                     `json:"-"`
		Number        math.HexOrDecimal64                        `json:"number"`
		GasUsed       math.HexOrDecimal64                        `json:"gasUsed"`
		ParentHash    common.Hash                                `json:"parentHash"`
		BaseFee       *math.HexOrDecimal256                      `json:"baseFeePerGas"`
		ExcessBlobGas *math.HexOrDecimal64                       `json:"excessBlobGas"`
		BlobGasUsed   *math.HexOrDecimal64                       `json:"blobGasUsed"`
	}
	var enc Genesis
	enc.Config = g.Config
	enc.Nonce = math.HexOrDecimal64(g.Nonce)
	enc.Timestamp = math.HexOrDecimal64(g.Timestamp)
	enc.ExtraData = g.ExtraData
	enc.GasLimit = math.HexOrDecimal64(g.GasLimit)
	enc.Difficulty = (*math.HexOrDecimal256)(g.Difficulty)
	enc.Mixhash = g.Mixhash
	enc.Coinbase = g.Coinbase
	if g.Alloc != nil {
		enc.Alloc = make(map[common.UnprefixedAddress]types.Account, len(g.Alloc))
		for k, v := range g.Alloc {
			enc.Alloc[common.UnprefixedAddress(k)] = v
		}
	}
	enc.AirdropHash = g.AirdropHash
	enc.AirdropAmount = (*math.HexOrDecimal256)(g.AirdropAmount)
	enc.AirdropData = g.AirdropData
	enc.Number = math.HexOrDecimal64(g.Number)
	enc.GasUsed = math.HexOrDecimal64(g.GasUsed)
	enc.ParentHash = g.ParentHash
	enc.BaseFee = (*math.HexOrDecimal256)(g.BaseFee)
	enc.ExcessBlobGas = (*math.HexOrDecimal64)(g.ExcessBlobGas)
	enc.BlobGasUsed = (*math.HexOrDecimal64)(g.BlobGasUsed)
	return json.Marshal(&enc)
}
